name: 'InnoSetupAction'
description: Generate installer files by Inno Setup for Windows platform
author: 'zhangt58'

inputs:
  filepath:
    description: 'Path for ISS file'
    required: true

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}\ISCC.exe ${{inputs.filepath}}
      shell: cmd
